### PR TITLE
Add requiresMainQueueSetup to fix warning in RN 0.49+

### PR DESCRIPTION
**Pull request by Naoto-Ida**
Please see [this](https://github.com/wix/react-native-navigation/issues/1982) for reference.

### CODE REVIEW

**Comment by stoneman1** [comment]
What does that exactly do? Expect removing the warning?

**Comment by Naoto-Ida** [comment]
@stoneman1 The warning stems from [here](https://github.com/facebook/react-native/blob/master/React/Base/RCTModuleData.mm#L67).

**Comment by ayercm** [comment]
I can see that it now gives a proper warning, but how will the underlying issue get fixed, in other words, what do we have to do to achieve "main queue setup" and avoid this breaking "in a future release of React Native?

**Comment by Naoto-Ida** [comment]
@ayercm So from my understanding, by returning `true` for `requiresMainQueueSetup`, we signify that this module interacts with UI directly. If we return `false` it will run on the background thread. Either way, I think we should define `requiresMainQueueSetup` here to suppress the warning, but we can discuss what the returning boolean should be.

**Pull request merged**
