### PR TITLE
add initialSpecificOrientation

### PR DESCRIPTION
**Pull request by pvinis**

### CODE REVIEW

**Comment by andrerfneves** [comment]
@pvinis we would need feature parity with the Android side of the package. Any chance you can update this PR to account for Android as well?

**Comment by pvinis** [comment]
i could look into it, but i have very little experience with android.
also, this package is not working very well, and its pretty reproducible, so i have to see what to do.

**Comment by andrerfneves** [comment]
@pvinis we know the package is not working very well. We just got a couple new maintainers and so we're working to solve the outstanding issues. I'll review your PR when I get a chance, lots to do right now. In the meantime, could you elaborate on your issues with this package by opening an Issue? I'd love to debug your use-case.

**Comment by andrerfneves** [comment]
Any updates here @pvinis?

**Comment by pvinis** [comment]
so I have replaced this library with a homebrew one I did. my case was I had a screen locked in portrait. then I navigate to a screen locked in landscape. sometimes that didn't work. then when it worked, when I moved back to the first screen, it would stay in landscape. so I decided I can fix it myself. I could send you what I did. it's not much different than this repo but I haven't actually tried to think of what's different.

**Comment by andrerfneves** [comment]
@pvinis that would be great. Would love to be able to improve on the package. I'm going to go ahead and close this then for now. Cheers.

**Comment by pvinis** [comment]
alright. I'm back from holidays next weekend so I will write back.

**Comment by YasirZillow** [comment]
This was very useful I needed this in iOS so used it. This should get merged. I created a question #345

**Comment by pvinis** [comment]
I'm not using this lib anymore, but feel free to use this PR for what you need.

**Pull request closed without merging**
