### PR TITLE
Updating to use Interface Orientation instead of Device Orientation

### PR DESCRIPTION
**Pull request by venk-aw**
This is related to issue 56

### CODE REVIEW

**Comment by yamill** [comment]
Awesome. Let me try this out today and I'll merge :+1: 

Thanks!

**Comment by Sh3rawi** [comment]
@venk-aw shouldn't this be changed as well? 
     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange:) name:@"UIDeviceOrientationDidChangeNotification" object:nil];

**Comment by yamill** [comment]
Good catch @Sh3rawi. @venk-aw ?

**Comment by venk-aw** [comment]
@Sh3rawi I don't think it needs to be changed.

**Comment by charliesbox** [comment]
please accept this pull request. im struggling with the orientation when device is on a flat surface. pretty urgent!

**Comment by ldom** [comment]
On my part, I have updated the code to use the Interface Orientation when the Device Orientation is Unknown. If anyone is interested, I can make a PR.

**Comment by toddmetheny** [comment]
@Idom I wouldn't mind seeing that and then making a choice b/w the two approaches. It's fewer changes?

**Comment by ldom** [comment]
@toddmetheny it's this one: https://github.com/yamill/react-native-orientation/pull/104

**Comment by andrerfneves** [comment]
`statusBarOrientation` has been deprecated according to Apple Docs:
https://developer.apple.com/documentation/uikit/uiapplication/1623026-statusbarorientation

**Pull request closed without merging**
