### PR TITLE
Added new methods to provide specific orientation information

### PR DESCRIPTION
**Pull request by pjcabrera**
I'm submitting a PR to get landscape-left and landscape-right orientation functionality. This is added as a new method so as not to break compatibility with the existing API. Also added new methods to lock to landscape-left and lock to landscape-right.

A previous PR I submitted had similar functionality but it broke API. These new methods are an extension of the current API and should not cause any breakage in existing code out there using this package.

### CODE REVIEW

**Comment by natorojr** [comment]
Awesome @pjcabrera! Thanks for being conscious about not breaking existing code. These API extensions seem very useful and I'll be making use of them in my current project as soon as this is merged 

+1

**Comment by danlopez** [comment]
This seems very useful and the API is aligned with the existing API. 

+1 from me

**Comment by yamill** [comment]
This is great. Thanks! :+1:

**Comment by yamill** [comment]
@pjcabrera can you also update the readme? thanks!

**Pull request merged**
