### PR TITLE
Fixes onHostResume crash

### PR DESCRIPTION
**Pull request by stoneman1**
Does what #154 without the updating headers. Cat made second commit sorry for that :)

### CODE REVIEW

**Comment by andrerfneves** [comment]
@stoneman1 have we tested this? I haven't faced any issues `onHostResume` before, but maybe I just haven't reached that state.

**Comment by stoneman1** [comment]
Some people where asking for this update. I have not had any issues so hard so say if it works. @StefanWallin could check it. He was saying something about this in #174

**Comment by StefanWallin** [comment]
I'm not gonna be in a position to test this as I'm going on vacation today. So ship and I'll get back to you in august. Just don't wait for me, I'll continue with my own fork which has the fix for the issue i mentioned in #174 in the mean time.

**Comment by andrerfneves** [comment]
@StefanWallin great. We'll actually hold off until other users have issues with this onHostResume in order to test/ship.

**Comment by JanPretzel** [comment]
I am experiencing the same issue as described in #103. Applying the changes from this PR fixes the issue for me.

**Comment by stoneman1** [comment]
Ok, we could then merge this.

**Comment by stoneman1** [comment]
@andrerfneves should we make new release then?

**Comment by andrerfneves** [comment]
@JanPretzel  @stoneman1 I'll send a new release to NPM shortly

**Pull request merged**
