### PR TITLE
Adds Android support

### PR DESCRIPTION
**Pull request by jaysoo**
This PR adds Android support for all of the documented `Orientation` methods.

Tested with react-native 0.16.0.

### CODE REVIEW

**Comment by jaysoo** [comment]
@yamill If you can take a quick look. We're looking to add this for our own RN app. :)

**Comment by skv-headless** [comment]
@jaysoo great work :+1:

**Comment by jaysoo** [comment]
@skv-headless Thanks :)

**Comment by yamill** [comment]
Thanks will push to npm shortly :+1: 

good job @jaysoo !

**Pull request merged**
