### PR TITLE
Update build.gradle for compatibility

### PR DESCRIPTION
**Pull request by jyliang**

### CODE REVIEW

**Comment by MrLoh** [comment]
Please merge this @yamill

**Comment by MateusAndrade** [comment]
There is any update about this? Without setting compileSdkVersion to 26 i cannot build my app with the release config

**Comment by NathanielWaggoner** [comment]
I don't think this guy is maintaining this repo anymore.  Anyone know if there's an active fork?

**Comment by MrLoh** [comment]
@yamill please respond

**Comment by MateusAndrade** [comment]
@MrLoh, @NathanielWaggoner  I think this repo is dead, i switched to this [react-native-orientation-locker](https://github.com/wonday/react-native-orientation-locker)(i think its a fork of the original project) and dont have this problem. I just needed to change my imports on gradle, js, etc. 

Hope it helps! =)

**Pull request closed without merging**
