### PR TITLE
Android - Specific Orientation Functionality

### PR DESCRIPTION
**Pull request by scgough**
Hi there - I've added in the Specific Orientation functionality for Android devices. It won't report back if the device is already locked to an orientation but will if not. I'm working on fixing that though...just not sure how possible it is yet!

### CODE REVIEW

**Comment by yamill** [comment]
This is definitely progress! Awesome! Thanks a lot :+1:

**Comment by scgough** [comment]
My colleagues and I might have found an issue with this @yamill 

Android seems to handle the reporting of orientation differently. i.e.

Iphone Method:  `device orientation` > (check locks) -> projected orientation -> transforms -> visual orientation
Android method: device orientation > (check locks) -> `projected orientation` -> transforms -> visual orientation

So...this would be why nothing gets reported from Android if we have a locked orientation. I think what we need to have is a check on the devices motion sensors and when a device hits a certain angle range report back to JS with an orientation...and keep doing so as it enters a new range (orientation). 

Looking into this at the moment but if so, it might be worth reverting the PR.

**Comment by yamill** [comment]
Thanks for looking into this! I've reverted the PR.

I need to get an Android device soon, so I can help with some of the contribution. I looking forward to a solution! Thanks again for all your input :+1:

**Comment by scgough** [comment]
hi @yamill I'm afraid I haven't had time to look at this yet but I hope to soon. I'll keep you posted as and when I can. Sorry I can't be more definitive.

**Pull request merged**
