### PR TITLE
Solves an error with rotation if the screen is already rotated in iOS

### PR DESCRIPTION
**Pull request by josepbordesjove**

### CODE REVIEW

**Comment by fluiddot** [comment]
This solution works really great!
Please check this PR 🙏

**Comment by jl-casella** [comment]
I agree, tested this solution and it works just great, if this PR could be merged to master, it would be great!

**Comment by crsunik** [comment]
Those changes prevents autorotation after unlocking all locks

**Comment by crsunik** [comment]
Does it works for you guys? I still have the same problem - screen is rotating, but not my ui - it is still locked

**Comment by suyuan-chang** [comment]
This fix doesn't work on unlockAllOrientations(). If unlockAllOrientations() is called after lockToPortrait(), screen UI can not rotate freely.

Apply the same workaround from lockTo*() to unlockAllOrientations() can solve this problem.

**Comment by jqn** [comment]
Same problem here

**Comment by arnibarnason** [comment]
This is still a bug since the change in the readme caused different [issues](https://github.com/yamill/react-native-orientation/issues/260) so it was changed back here #261.

**Comment by mmaschenko** [comment]
This is still an issue, when you launch app while mobile is in 'landscape' mode it rotates app to landscape even in xcode it is blocked

**Pull request merged**
