### PR TITLE
Feature/add screen size notification option

### PR DESCRIPTION
**Pull request by jstheoriginal**
Often React Native's `Dimensions.get('window')` width and height values are not correct for the new orientation at the moment when the orientation listeners are triggered. 

This listener will return orientation, screenWidth and screenHeight when orientation changes. The screen width/height are from the native OS rather than what React Native reports.

Use it if you need to re-layout your UI for the new orientation when you are using dimension values relative to the screen's width/height. i.e. Centering a dynamically-sized modal in a view.

### CODE REVIEW

**Comment by andrerfneves** [comment]
Awesome @jstheoriginal, going to look this over and test it out! Great feature addition

**Comment by andrerfneves** [comment]
@jstheoriginal sorry about the delay. Got pretty busy with conference and work. Going to have time this week to test this out and review/merge.

**Comment by stoneman1** [comment]
@andrerfneves did you have the time to test this out?

**Comment by andrerfneves** [comment]
@stoneman1 https://github.com/yamill/react-native-orientation/pull/190#issuecomment-354931733

**Pull request closed without merging**
