### PR TITLE
Update build.gradle build tools version

### PR DESCRIPTION
**Pull request by Brian-Kaplan**
build tools version is old, please merge to update

### CODE REVIEW

**Comment by Brian-Kaplan** [comment]
@yamill please merge this. I need a higher build tools version for my project.

**Comment by andrerfneves** [comment]
@Brian-Kaplan you should be able to use diff build tools for each project in your react native application. The android-sdk should automatically download any missing dependencies. We can however upgrade this. Need to test and make sure everything still works smooth before merging.

**Comment by Brian-Kaplan** [comment]
@andrerfneves could you describe in more detail how I can have different build tools versions for different projects?

My application uses 25.0.2 and this project uses 23.0.1
When I include the project as described in your README my android studio tells me the minimum required is 25.0.0

I think what you're saying about different projects with different build tools versions coexisting only works for certain build tools versions. Looks like 25.0.2 and 23.0.1 are not compatible

**Comment by Brian-Kaplan** [comment]
@andrerfneves where are the tests that need to be run? Btw build tools version really won't affect the code in anyway.

**Comment by Brian-Kaplan** [comment]
I've decided to not use the android implementation for this project.

**Pull request closed without merging**
